// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class Cities extends Building {
	/**
	 * 
	 */
	private int points;

	/**
	 * 
	 * @return 
	 */
	public int getPoints() {
	}

	/**
	 * 
	 * @param owner 
	 */
	public void Cities(Player owner) {
	}
}
