// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class City extends Building {
	/**
	 * 
	 * @param owner 
	 */
	public void Cities(Player owner) {
	}
}
