// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public interface Command {
	/**
	 * 
	 */
	public void execute();

	/**
	 * 
	 */
	public void redo();

	/**
	 * 
	 */
	public void undo();
}
