// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class ComputerPlayer extends Player {
	/**
	 * 
	 */
	private int randomInt;
	/**
	 * 
	 */
	private boolean hadRolled;

	/**
	 * 
	 * @param playerId 
	 */
	public void ComputerPlayer(int playerId) {
	}
}
