// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public interface DiceRollObserver {
	/**
	 * 
	 * @param diceValue 
	 */
	public void onDiceRolled(int diceValue);
}
