// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class Road {
	/**
	 * 
	 */
	private Node[] connectedNodes;
	/**
	 * 
	 */
	private Player owner;

	/**
	 * 
	 * @param node 
	 * @return 
	 */
	public boolean isConnected(Node node) {
	}

	/**
	 * 
	 * @return 
	 */
	public Node[] getConnectedNodes() {
	}

	/**
	 * 
	 * @param nodes 
	 * @param owner 
	 */
	public void Roads(Node nodes, Player owner) {
	}

	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
	}
}
