// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class RobberActionsManager {
	/**
	 * 
	 */
	private Tile currentTile;
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private int rand;
	/**
	 * 
	 */
	private Resources[] STEAL_RESOURCES;

	/**
	 * 
	 * @return 
	 */
	public boolean discardResourceCards() {
	}

	/**
	 * 
	 * @param board 
	 * @return 
	 */
	public boolean moveRobber(Board board) {
	}

	/**
	 * 
	 * @return 
	 */
	public Tile getCurrentTile() {
	}

	/**
	 * 
	 * @param currentPlayer 
	 * @param victimPlayer 
	 */
	public void stealResource(Player currentPlayer, Player victimPlayer) {
	}

	/**
	 * 
	 * @param board 
	 * @param players 
	 */
	public void RobberActionsManager(Board board, Player players) {
	}

	/**
	 * 
	 * @param currentPlayer 
	 * @return 
	 */
	public Player chooseVictim(Player currentPlayer) {
	}

	/**
	 * 
	 * @param  
	 * @return 
	 */
	public boolean isRobberOnTile(Tile ) {
	}
}
