// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class StateWriter {
	/**
	 * 
	 * @param board 
	 * @param robberManager 
	 */
	public void writeState(Board board, RobberActionsManager robberManager) {
	}
}
