// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int tileID;
	/**
	 * 
	 */
	private int token;
	/**
	 * 
	 */
	private Resources resource;
	/**
	 * 
	 */
	public Node[] node;
	/**
	 * 
	 */
	public DiceRollObserver dicerollobserver;
	/**
	 * 
	 */
	public RobberActionsManager robber;
	/**
	 * 
	 */
	public GameLogger logger;
	/**
	 * 
	 */
	public GameLogger gamelogger;

	/**
	 * 
	 * @param resource 
	 * @param id 
	 * @param token 
	 */
	public void Tile(Resources resource, int id, int token) {
	}

	/**
	 * 
	 * @return 
	 */
	public Resources getResource() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getTileId() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getToken() {
	}

	/**
	 * 
	 * @return 
	 */
	public Node[] getNodes() {
	}

	/**
	 * 
	 * @param nodes 
	 */
	public void setNodes(Node nodes) {
	}

	/**
	 * 
	 * @param diceValue 
	 */
	public void onDiceRolled(int diceValue) {
	}

	/**
	 * 
	 * @param diceValue 
	 * @return 
	 */
	public boolean shouldSkipTile(int diceValue) {
	}

	/**
	 * 
	 * @param n 
	 */
	private void distributeResourceToPlayer(Node n) {
	}

	/**
	 * 
	 */
	private void distributeResources() {
	}

	/**
	 * 
	 * @param robber 
	 */
	public void setRobberManager(RobberActionsManager robber) {
	}

	/**
	 * 
	 * @param logger 
	 */
	public void setLogger(GameLogger logger) {
	}
}
