// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class TurnManager {
	/**
	 * 
	 */
	private TurnManagerStates currentState;
	/**
	 * 
	 */
	public TurnManagerStates turnmanagerstates;
	/**
	 * 
	 */
	public RobberActionsManager robberactionsmanager;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private GameLogger logger;
	/**
	 * 
	 */
	private MultiDice dice;
	/**
	 * 
	 */
	public Dice dice;
	/**
	 * 
	 */
	public StateWriter statewriter;
	/**
	 * 
	 */
	public CommandManager commandmanager;

	/**
	 * 
	 * @param board 
	 * @param logger 
	 * @param dice 
	 * @param robberManager 
	 */
	public void TurnManager(Board board, GameLogger logger, Dice dice, RobberActionsManager robberManager) {
	}

	/**
	 * 
	 * @param input 
	 * @param player 
	 */
	public void manageTurn(UserInput input, Player player) {
	}

	/**
	 * 
	 * @return 
	 */
	public int rollMultiDice() {
	}

	/**
	 * 
	 * @param player 
	 */
	public void executeTurn(Player player) {
	}

	/**
	 * 
	 * @param player 
	 */
	private void handleRoll(Player player) {
	}

	/**
	 * 
	 * @param player 
	 */
	private void handleList(Player player) {
	}

	/**
	 * 
	 * @param player 
	 * @param nodeId 
	 */
	private void handleBuildSettlement(Player player, int nodeId) {
	}

	/**
	 * 
	 * @param player 
	 * @param nodeId 
	 */
	private void handleBuildCity(Player player, int nodeId) {
	}

	/**
	 * 
	 * @param player 
	 * @param fromNodeId 
	 * @param toNodeId 
	 */
	private void handleBuildRoad(Player player, int fromNodeId, int toNodeId) {
	}

	/**
	 * 
	 * @param player 
	 */
	private void isValidAction(Player player) {
	}

	/**
	 * 
	 * @param player 
	 */
	private void roll(Player player) {
	}

	/**
	 * 
	 * @param player 
	 */
	private void handleGo(Player player) {
	}
}
