// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class ActionEvaluator {
	/**
	 * 
	 */
	private RuleBasedAI player;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	public RuleBasedAI rulebasedai;

	/**
	 * 
	 * @return 
	 */
	private int[] getBuildableRoads() {
	}

	/**
	 * 
	 * @return 
	 */
	public AIAction[] evaluate() {
	}

	/**
	 * 
	 * @param board 
	 */
	public void setBoard(Board board) {
	}

	/**
	 * 
	 * @param player 
	 */
	public void ActionEvaluator(RuleBasedAI player) {
	}
}
