// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class AIAction {
	/**
	 * 
	 */
	private UserInput action;
	/**
	 * 
	 */
	private int node1;
	/**
	 * 
	 */
	private int node2;
	/**
	 * 
	 */
	private EDouble value;

	/**
	 * 
	 * @param action 
	 * @param node1 
	 * @param node2 
	 * @param value 
	 */
	public void AIAction(UserInput action, int node1, int node2, EDouble value) {
	}
}
