// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class BuildCityCommand {
	/**
	 * 
	 */
	private int nodeId;

	/**
	 * 
	 * @param board 
	 * @param player 
	 * @param nodeId 
	 */
	public void BuildCityCommand(Board board, Player player, int nodeId) {
	}
}
