// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public abstract class Building {
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private int points;

	/**
	 * 
	 * @param building 
	 */
	public void Building(Building building) {
	}

	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getPoints() {
	}
}
