// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class BuildRoadCommand {
	/**
	 * 
	 */
	private int nodeId1;
	/**
	 * 
	 */
	private int nodeId2;

	/**
	 * 
	 * @param board 
	 * @param player 
	 * @param nodeId1 
	 * @param nodeId2 
	 */
	public void BuildRoadCommand(Board board, Player player, int nodeId1, int nodeId2) {
	}
}
