// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class CommandManager {
	/**
	 * 
	 */
	private int currentCommand;
	/**
	 * 
	 */
	public Command[] command;

	/**
	 * 
	 */
	public void CommandManager() {
	}

	/**
	 * 
	 * @param command 
	 */
	public void executeCommand(Command command) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean undo() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean redo() {
	}
}
