// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class ConstraintChecker {
	/**
	 * 
	 */
	private RuleBasedAI player;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private Player[] allPlayers;
	/**
	 * 
	 */
	public RuleBasedAI rulebasedai;
	/**
	 * 
	 */
	public Player player;

	/**
	 * 
	 * @param player 
	 */
	public void ConstraintChecker(RuleBasedAI player) {
	}

	/**
	 * 
	 * @param board 
	 */
	public void setBoard(Board board) {
	}

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	private int getLongestRoadLength(Player player) {
	}

	/**
	 * 
	 * @return 
	 */
	private int[] getBuildableRoads() {
	}

	/**
	 * 
	 * @return 
	 */
	private PlayerCommand checkLongestRoadConstraint() {
	}

	/**
	 * 
	 * @return 
	 */
	private PlayerCommand checkRoadConnectionConstraint() {
	}

	/**
	 * 
	 * @return 
	 */
	private PlayerCommand checkCardConstraint() {
	}

	/**
	 * 
	 * @return 
	 */
	public PlayerCommand check() {
	}

	/**
	 * 
	 * @param player 
	 */
	public void setAllPlayer(int[] player) {
	}
}
