// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public abstract class DiceRollSubject {
	/**
	 * 
	 */
	public DiceRollObserver[] observers;

	/**
	 * 
	 * @param ob 
	 */
	public void addObserver(DiceRollObserver ob) {
	}

	/**
	 * 
	 * @param ob 
	 */
	public void removeObserver(DiceRollObserver ob) {
	}

	/**
	 * 
	 * @param diceValue 
	 */
	protected void notifyObservers(int diceValue) {
	}
}
