// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private int roundsPlayed;
	/**
	 * 
	 */
	private int maxRounds;
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	public TurnManager turnmanager;
	/**
	 * 
	 */
	public GameLogger gamelogger;
	/**
	 * 
	 */
	public StateWriter statewriter;
	/**
	 * 
	 */
	public MultiDice dice;

	/**
	 * 
	 */
	public void start() {
	}

	/**
	 * 
	 */
	public void playRound() {
	}

	/**
	 * 
	 * @param players 
	 * @param maxRounds 
	 * @param logger 
	 */
	public void Game(Player players, int maxRounds, GameLogger logger) {
	}
}
