// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class GameLogger {
	/**
	 * 
	 */
	private int rounds;

	/**
	 * 
	 */
	public void GameLogger() {
	}

	/**
	 * 
	 * @param playerId 
	 * @return 
	 */
	private String start(int playerId) {
	}

	/**
	 * 
	 * @param player 
	 * @param action 
	 */
	public void log(int player, String action) {
	}

	/**
	 * 
	 */
	public void endTurn() {
	}
}
