// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class HumanPlayer extends Player {
	/**
	 * 
	 */
	private String scanner;
	/**
	 * 
	 */
	public UserInput userinput;
	/**
	 * 
	 */
	private int hasRolled;
	/**
	 * 
	 */
	public PlayerCommand playercommand;

	/**
	 * 
	 * @param playerId 
	 * @param logger 
	 */
	public void HumanPlayer(int playerId, GameLogger logger) {
	}
}
