// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int nodeId;
	/**
	 * 
	 */
	private Building building;
	/**
	 * 
	 */
	private Node[] adjacentNodes;

	/**
	 * 
	 * @param id 
	 */
	public void Node(int id) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
	}

	/**
	 * 
	 * @return 
	 */
	public Building getBuilding() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getNodeId() {
	}

	/**
	 * 
	 * @param Building 
	 */
	public void setBuilding(Building Building) {
	}

	/**
	 * 
	 * @param node 
	 */
	public void addAdjacentNode(Node node) {
	}

	/**
	 * 
	 * @return 
	 */
	public Node getAdjacentNodes() {
	}
}
