// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class PlayerCommand {
	/**
	 * 
	 */
	public UserInput action;
	/**
	 * 
	 */
	private Node node1;
	/**
	 * 
	 */
	private Node node2;

	/**
	 * 
	 * @param action 
	 * @param node2 
	 * @param node1 
	 */
	public void PlayerCommand(UserInput action, Node node2, Node node1) {
	}

	/**
	 * 
	 * @return 
	 */
	public UserInput getAction() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getNodeOne() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getNodeTwo() {
	}
}
