// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class RuleBasedAI extends ComputerPlayer {
	/**
	 * 
	 */
	private GameLogger logger;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private ActionEvaluator actionEvaluator;
	/**
	 * 
	 */
	private ConstraintChecker constraintChecker;
	/**
	 * 
	 */
	public ActionEvaluator actionevaluator;
	/**
	 * 
	 */
	public ConstraintChecker constraintchecker;
	/**
	 * 
	 */
	public Board board;

	/**
	 * 
	 * @param playerId 
	 * @param logger 
	 */
	public void RuleBasedAI(Player playerId, GameLogger logger) {
	}

	/**
	 * 
	 * @param board 
	 */
	public void setBoard(Board board) {
	}

	/**
	 * 
	 * @param players 
	 */
	public void setAllPlayers(Player[] players) {
	}

	/**
	 * 
	 * @return 
	 */
	public PlayerCommand takeTurn() {
	}
}
