// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public class tileToNodesMapEntry {
	/**
	 * 
	 */
	private Node[] value;
	/**
	 * 
	 */
	private Tile key;
}
