// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Assignment1_Team5;

/************************************************************/
/**
 * 
 */
public enum TurnManagerStates {
	/**
	 * 
	 */
	START_TURN,
	/**
	 * 
	 */
	DO_ACTION,
	/**
	 * 
	 */
	END_TURN;
}
